### ISSUE TITLE
Could not find org.spigotmc:spigot-api:1.19.2-R0.1-SNAPSHOT

### ISSUE THREAD

**Issue by theguywhoburns** [xenondevs/Nova-Addon-Template#2]
A problem occurred configuring root project 'example'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find org.spigotmc:spigot-api:1.19.2-R0.1-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot-api/1.19.2-R0.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot-api/1.19.2-R0.1-SNAPSHOT/spigot-api-1.19.2-R0.1-SNAPSHOT.pom
       - https://repo.xenondevs.xyz/releases/org/spigotmc/spigot-api/1.19.2-R0.1-SNAPSHOT/maven-metadata.xml
       - https://repo.xenondevs.xyz/releases/org/spigotmc/spigot-api/1.19.2-R0.1-SNAPSHOT/spigot-api-1.19.2-R0.1-SNAPSHOT.pom
       - file:/C:/Users/������/.m2/repository/org/spigotmc/spigot-api/1.19.2-R0.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/������/.m2/repository/org/spigotmc/spigot-api/1.19.2-R0.1-SNAPSHOT/spigot-api-1.19.2-R0.1-SNAPSHOT.pom
     Required by:
         project : > xyz.xenondevs.nova.nova-gradle-plugin:xyz.xenondevs.nova.nova-gradle-plugin.gradle.plugin:0.12 > xyz.xenondevs.nova:nova-gradle-plugin:0.12

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
im stupid so how to fix that?

**Comment by ByteZ1337** [comment]
BuildTools probably built Spigot 1.19.3 since that was released 2 days ago and thus is the latest version. You can either wait until Nova is ported to 1.19.3 or run BuildTools with the `--rev 1.19.2` argument

**Comment by theguywhoburns** [comment]
> BuildTools probably built Spigot 1.19.3 since that was released 2 days ago and thus is the latest version. You can either wait until Nova is ported to 1.19.3 or run BuildTools with the `--rev 1.19.2` argument

It was building spigot 1.19.2(cuz 1.19.3 is latest but not stable) but it wanted to install the mojang mapped version, i fixed it by adding the missing characters to the name of the core.

**Comment by theguywhoburns** [comment]
> > BuildTools probably built Spigot 1.19.3 since that was released 2 days ago and thus is the latest version. You can either wait until Nova is ported to 1.19.3 or run BuildTools with the `--rev 1.19.2` argument
> 
> It was building spigot 1.19.2(cuz 1.19.3 is latest but not stable) but it wanted to install the mojang mapped version, i fixed it by adding the missing characters to the name of the core.

In 1 word i fixed it, and i have another question, where can i get beginner friendly guide?
